### ISSUE TITLE
Request for additional icons.

### ISSUE THREAD

**Issue by saipraveenbammidi** [WaifuPX-DG/DGicons#1]
Hey there good work with the application.
Can you also these below applications in then next update?

com.fenchtose.reflog

com.ivy.wallet

com.fsck.k9

dev.sasikanth.pinnit

com.michaldrabik.showly2

com.otraku.app

nl.viter.glider

io.github.forkmaintainers.iceraven

app.nekko.to

de.bendix.flux

com.phonepe.app

dev.netlob.spotistats

com.windscribe.vpn

com.literal

**Comment by saipraveenbammidi** [comment]
and also btw you may have issues finding the below app logos, so here ya go.

Otraku - com.otraku.app

![com.otraku.app.png](https://user-images.githubusercontent.com/55645257/173921003-02313fae-189e-44ff-bd49-d8ef2f09454f.png)

IceRaven -  io.github.forkmaintainers.iceraven


![io.github.forkmaintainers.iceraven.png](https://user-images.githubusercontent.com/55645257/173921088-2a24a8f3-7ffd-4263-b72c-d3009522443c.png)

Neko - app.nekko.to

![app.nekko.to.png](https://user-images.githubusercontent.com/55645257/173921151-3be81438-7488-4077-ace5-dbc696dc7820.png)

Literal club - com.literal

![com.literal.png](https://user-images.githubusercontent.com/55645257/173921176-e439e16d-d9a5-493e-9138-647c626363b4.png)

**Comment by WaifuPX-DG** [comment]
thank you, i really appreciate it

**Comment by WaifuPX-DG** [comment]
All icons have been added.
