### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Shivelight** [WaifuPX-DG/DGicons#13]
Requesting icons for the following apps:

LibreTorrent
org.proninyaroslav.libretorrent

Wiz
com.tao.wiz

MyAnimeList
net.myanimelist.app

tiket.com
com.tiket.gits

MyJDownloader
org.appwork.myjdandroid

myIndiHome
com.telkom.indihome.external

App Settings (https://github.com/BlueCat300/XposedAppSettings)
de.robv.android.xposed.mods.appsettings
ru.bluecat.android.xposed.mods.appsettings

PowerTube (https://github.com/razar-dev/PowerTube)
ussr.razar.youtube_dl

WA Tweaker (https://watweaker.com)
com.alex193a.watweaker

Momo (https://t.me/magiskalpha/517)
io.github.vvb2060.mahoshojo

Thank you for your consideration!

**Comment by WaifuPX-DG** [comment]
Your request icons have been added.
