### ISSUE TITLE
Samsung calendar icon issue 

### ISSUE THREAD

**Issue by kahanzammi** [WaifuPX-DG/DGicons#14]
I'm not sure this is related to the icon pack or lawnchair.  While Google calendar icon is correctly displaying the current date(27), Samsung calendar is displaying a completely different date (11).

![Screenshot_20220727-212127_Lawnchair](https://user-images.githubusercontent.com/105884763/181310941-a3728fb6-d512-4dcc-b9e2-a37b04fdcbdb.jpg)

**Comment by WaifuPX-DG** [comment]
(11) is shown because it is a static icon, Google calendar shows (27) because it is dynamic, Whether it is dynamic or not depends on the clock app, although you can make the Samsung Calendar icon dynamic by applying any adaptive Icon pack along with dgicons.

**Comment by WaifuPX-DG** [comment]
![Screenshot_2022-07-27-12-54-59-349_app lawnchair](https://user-images.githubusercontent.com/78942037/181339874-ca9bc776-126e-452b-835c-dff06049512f.png)
Using an adaptive icon pack (for example pix) together with dgicons you will get Dynamic Calendar Icons
