### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by muntasimfuad** [WaifuPX-DG/DGicons#21]
**App Name :** DetoxDroid (https://github.com/flxapps/DetoxDroid)
 
**App Pakage Name :** com.flx_apps.digitaldetox 
________________________________________

**App Name :** Notesnook (https://github.com/streetwriters/notesnook)

**App Pakage Name :** com.streetwriters.notesnook

**Comment by WaifuPX-DG** [comment]
Your request has been completed, it will be available in the next version (Haku) that will be published in a few days. Thank you for using DGicons.
