### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Luedgiary89** [WaifuPX-DG/DGicons#25]
Th ese are the icons that remain to be adapted:

GCam Pixel3modX
com.google.android.Pixel3ModX

Notas Moto (Moto Notes) [Original y Port]
com.motorola.stylus

Calendario Moto (Moto Calendar)
com.motorola.cn.calendar

Reloj Moto (Moto Clock)
com.motorola.cn.deskclock

Teléfono Moto (Moto Dialer) [original y Port]
com.motorola.dialer

Archivos Moto/Lenovo (Moto/Lenovo Files)
com.zui.filemanager (para Lenovo)

Calculadora Moto (Moto Calculator)
com.motorola.cn.calculator

Revanced YMusic
app.revanced.android.apps.youtube.music

**Comment by WaifuPX-DG** [comment]
all icons have been linked, they will be available in the next version (Haku) will be published in a few days. Thank you for using DGicons
