### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by watham15** [WaifuPX-DG/DGicons#5]
Hi, I had these app icons to request

HMA VPN
com.hidemyass.hidemyassprovpn

Today Weather
mobi.lockdown.weather

Windscribe VPN
com.windscribe.vpn

Wallipop
com.arrow.wallpapers.wallipop

Mpv player
is.xyz.mpv

HManager
com.chsappz.hmanager

**Comment by WaifuPX-DG** [comment]
All icons have been added.
